### ISSUE TITLE
crates-index-diff 0.11 and zlib-ng-compat

### ISSUE THREAD

**Issue by jonhoo** [Byron/crates-index-diff-rs#18]
I noticed that 0.11 (probably accidentally) enables the `zlib-ng` feature of `libz-sys` without a way to turn that off. Specifically:

`crates-index-diff` takes a dependency on `git-repository` with default features here:

https://github.com/Byron/crates-index-diff-rs/blob/01ca770ba0e2fd14994c6ca5ba1ecfa6c0349fa3/Cargo.toml#L18

`git-repository` has the `max-performance` feature by default, which includes `max-performance-safe`, which enables `git-features/zlib-ng-compat`:

https://github.com/Byron/gitoxide/blob/85a3bedd68d2e5f36592a2f691c977dc55298279/git-repository/Cargo.toml#L70

`git-features` in turn has that feature forward to `flate2/zlib-ng-compat` here:

https://github.com/Byron/gitoxide/blob/85a3bedd68d2e5f36592a2f691c977dc55298279/git-features/Cargo.toml#L45

which in turn enables the `zlib-ng` feature of `libz-sys`

Was this enable-without-opt-out intentional? If not, would you be okay with making this feature optional in crates-index-diff as well? I can submit a PR if that'd be helpful!

**Comment by Byron** [comment]
Thanks for bringing this to my attention!

> Was this enable-without-opt-out intentional?

I don't know what the right answer would be given that I didn't think about it at all 😅. The lesson to learn here might be that libraries should be mindful about the dependencies they pull in and prefer to leave the choice to the downstream users, either by forwarding features or by letting them configure features themselves.

> If not, would you be okay with making this feature optional in crates-index-diff as well? I can submit a PR if that'd be helpful!

I'd love that, primarily because I see enormous value of you getting your hands on `gitoxide`, indirectly or not 😁.

Here I would prefer forwarding features so the downstream isn't exposed to the nitty-gritty details. This would probably mean to configure `git-features` here similar to [this example](https://github.com/Byron/gitoxide/blob/85a3bedd68d2e5f36592a2f691c977dc55298279/experiments/diffing/Cargo.toml#L13-L12) and then adjust its selected features according to the ones forward by this crate. That would yield a specific solution to this problem with the option to extend it in future.

I could also imagine to add more documentation to explain to the downstream how they should configure `gitoxide` to their liking if you'd rather leave all control to them.

It's a choice you are probably more qualified to make. Thanks

**Comment by Byron** [comment]
I assume this question is answered, please feel free to keep commenting here though if anything comes up.

**Comment by jonhoo** [comment]
I think this is probably still relevant, I just haven't had any spare cycles to look at it sadly :sweat_smile:
