### ISSUE TITLE
crates-index-diff 0.11.1 produces `Added`, not `Yanked` for immediately-yanked crate version

### ISSUE THREAD

**Issue by jonhoo** [Byron/crates-index-diff-rs#19]
I'm running `crates-index-diff 0.11.1` over an index where the first commit is empty, and the second commit is
```diff
diff --git a/al/lo/allowed b/al/lo/allowed
new file mode 100644
index 0000000..b30662b
--- /dev/null
+++ b/al/lo/allowed
@@ -0,0 +1 @@
+{"name":"allowed","vers":"1.0.0","deps":[],"features":{},"cksum":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","yanked":true}
```

 This used to produce a `Changed::Yanked`, but with 0.11.1 it produces `Changed::Added` instead. Which isn't specifically _wrong_, but it is a change in behavior I didn't expect and isn't [in the changelog](https://github.com/Byron/crates-index-diff-rs/blob/main/CHANGELOG.md). I honestly don't know which it should produce. Maybe both, one immediately following the other? Figured I should at least document the change in behavior, and perhaps we should add a test for it?

**Comment by Byron** [comment]
Thanks for reporting! This is indeed a bug which has been squelched in [the latest release](https://github.com/Byron/crates-index-diff-rs/releases/tag/v11.1.1).

The diff was most helpful as it allowed to [improve the test suite](https://github.com/Byron/crates-index-diff-rs/commit/89378e10b395cb1c0d963557d46568fda7b49f7b) to check for this case. Even though such a case might already been present in the current sample set, I thought it was good to test the flexibility of the new test system. It turns out a diff is all that it takes :).

I am closing this in confidence the issue has been fixed, but please let me know if that isn't the case or if something else comes up. Thank you.
