### ISSUE TITLE
Allow peeking at the contents of a change before marking it as seen

### ISSUE THREAD

**Issue by jyn514** [Byron/crates-index-diff-rs#5]
See https://github.com/rust-lang/docs.rs/issues/626 - we would like to have error recovery in case we crash before we get a chance to process the new data. If we could look at the changes without marking them as seen, then have them show up the next time we call `fetch_changes()` unless we call a new `last_seen()` method, that would be very helpful.

**Comment by Byron** [comment]
Hi @jyn514 ,

I am happy to help and plan to have implemented this by the end of the weekend.
It would be like this:
* call `peek_changes()` to see what would be returned by `fetch_changes()`. It returns the `Object` (git commit) to which `fetch_changes()` would put the reference to keep track of what was last seen.
* The returned `Object` can then be used to advance the last-seen reference to that object when `fetch_changes()` shouldn't be called. Otherwise `fetch_changes()` will fetch and return all changes thus far.

With all the methods available, I believe one has perfect control over the behaviour, even though that will require a little more git interaction which usually is hidden behind `fetch_changes()`.

Please let me know your thoughts especially if there are concerns.

**Comment by jyn514** [comment]
Just repeating so I'm sure I understand:

- fetch_changes will keep the current behavior
- peek_changes will return an Object that represents the latest available commit, but does not change the `last_seen` commit.
- Object will have a `update_last_seen` method which changes the `last_seen` commit to that of the object.

That all sounds reasonable to me. I assume the object will also include all changes since the last_seen commit? If so that would meet all my needs :)

**Comment by Byron** [comment]
😅Indeed, that's correct and I did mean to say that `peek_changes()` will also return the changes seen until the `Object` it returns as well, so that if one would set `last_seen_reference()` to that `Object`, it would be exactly as if `fetch_changes()` had been called.

The API for that will 'just' be git, but I will try to provide an example or at least point to the tests here.

**Comment by Byron** [comment]
Version 5.1.0 was released with the requested changes. Have a look at the [the changelog](https://github.com/Byron/crates-index-diff-rs/blob/99c33e6936dadd7b3ab0af6709791a8cbdda2071/changelog.md#L3) for more information.

**Comment by jyn514** [comment]
Thank you so much for your help and your quick response!

**Comment by Byron** [comment]
What a coincidence that I am now in need for this very same feature!
In the process of this I noticed that one would want to set the 'last_seen_reference' to the OID that was previously peeked to, so now there is a method for just that. Have a look at [my code](https://github.com/crates-io/criner/blob/37b2b3568aa167c55263b442ca63056d5a708cdd/criner/src/engine/stage/changes.rs#L113) for an example - maybe it's useful to you as well.
