### ISSUE TITLE
Configurable index location

### ISSUE THREAD

**Issue by Nemo157** [Byron/crates-index-diff-rs#8]
To support usecases like https://github.com/rust-lang/docs.rs/issues/767 it would be useful to be able to specify the upstream url to be used in a function like `Index::from_path_or_cloned`.

The biggest unknown I see is what to do if it doesn't match. Currently if you setup a clone with the correct upstream remote name it will be just used, even if that remote doesn't match the one that would be cloned. I think with this function it would make more sense to verify that, and either change it or error if it is different.

(This could also be handled relatively easily on the docs.rs side by doing the git operations ourselves, if you think this is niche enough to not support).

**Comment by Byron** [comment]
Thanks for reporting, it's always a pleasure to help solving problems of docs.rs!

What's straight-forward is to extend the API to allow passing some options to specify the upstream URL.

Validation is a deceptively simple feature which is probably hard to get right, if it's more than a plain string comparison. The latter would certainly course fail in case of equivalent URLs, like `ssh://git@github.com/foo/bar`, `https://github.com/foo/bar`, or `https://github.com/foo/bar.git`.

The question of what should happen if validation fails to me can only be answered with aborting the operation, instead of trying to make the existing repository your own.

So my suggestion is to start with simple string-based URL comparison in case the repository exists and if there really is a need, beef that up to be a little smarter to handle equivalent URLs correctly.

**Comment by Byron** [comment]
Version 7.1 was just released to crates.io, adding `Index::from_path_or_cloned_with_options(…)` which for now allows to specify the URL to clone from. Simple string-based validation was added, too, just in case.

I hope it works for your, and if not it should be quick to make the necessary adjustments.
